<?php

use Krystal\Form\Element;
use Rentcar\Collection\GenderCollection;
use Rentcar\Collection\PaymentMethodCollection;

$genderCol = new GenderCollection();
$payMethCol = new PaymentMethodCollection();

$genders = $genderCol->getAll();
$methods = $payMethCol->getAll();

?>

<form action="<?= $this->url('Rentcar:Car@bookAction'); ?>" method="POST">
    <div class="row">
        <div class="col-lg-7 mr-3">
            <fieldset>
                <legend><?php $this->show('Client information'); ?></legend>

                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label><?php $this->show('Full name'); ?></label>
                            <?= Element::text('booking[name]', null, ['class' => 'form-control', 'placeholder' => $this->translate('Type as in your passport')]); ?>
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="form-group">
                            <label><?php $this->show('Gender'); ?></label>
                            <?= Element::select('booking[gender]', $this->translateArray($genders), null, ['class' => 'form-control']); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label><?php $this->show('Email'); ?></label>
                            <?= Element::text('booking[email]', null, ['class' => 'form-control', 'placeholder' => $this->translate('For notifications')]); ?>
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="form-group">
                            <label><?php $this->show('Phone'); ?></label>
                            <?= Element::text('booking[phone]', null, ['class' => 'form-control', 'placeholder' => $this->translate('For contacts if needed')]); ?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label><?php $this->show('Payment method'); ?></label>
                    <?= Element::select('booking[method]', $this->translateArray($methods), null, ['class' => 'form-control']); ?>
                </div>

                <div class="form-group">
                    <label><?php $this->show('Additional wishes '); ?></label>
                    <?= Element::textarea('booking[comment]', null, ['class' => 'form-control', 'rows' => 6, 'placeholder' => $this->translate('Do you have extra wishes?')]); ?>
                </div>
            </fieldset>
        </div>

        <div class="col-lg-4">
            <fieldset>
              <legend class="mb-4"><?php $this->show('Extra services'); ?> <small class="text-muted">(<?= $car->getServiceCount(); ?>)</small></legend>

              <?php foreach ($car->getServices() as $service): ?>
              <?php $id = sprintf('service-%s', $service->getId()); ?>

              <div class="form-group">
                <div class="custom-control custom-checkbox">
                  <?= Element::checkbox(sprintf('service[%s]', $service->getId()), $service->getId(), ['class' => 'custom-control-input', 'id' => $id], false); ?>
                  <label class="custom-control-label" for="<?= $id; ?>"><?= $service->getName(); ?></label>
                </div>
              </div>
              <?php endforeach; ?>

            </fieldset>
        </div>
    </div>

    <?= Element::hidden('csrf-token', $csrfToken); ?>
    <?= Element::hidden('booking[car_id]', $carId); ?>
    <?= Element::submit($this->translate('Book now'), ['class' => 'btn btn-lg btn-primary']); ?>
</form>