<section>
    <h2><?= $page->getName(); ?></h2>

    <div class="row align-items-start">
        <aside class="col-lg-7 mr-2">
            <div class="row">
                <?php foreach ($cars as $car): ?>
                <div class="col-lg-6 bg-white p-4">
                    <a href="<?= $car->getUrl(); ?>" class="d-block mb-4">
                        <img class="img-fluid img-thumbnail" src="<?= $car->getImageUrl('350x350'); ?>" alt="<?= $car->getName(); ?>">
                    </a>

                    <p class="text-muted text-center"><?= $car->getName(); ?></p>
                </div>
                <?php endforeach; ?>
            </div>
        </aside>

        <aside class="col-lg-4 bg-light p-4">
            <?= $this->loadPartial('search'); ?>
        </aside>
    </div>
</section>