<section class="mb-5 mt-5">
    <h2><?= $car->getName(); ?></h2>

    <div class="row align-items-start">
        <aside class="col-7 mr-5">
            <div class="row">
                <div class="col-6">
                    <img src="<?= $car->getImageUrl('350x350'); ?>" class="img-fluid d-block mx-auto" />
                </div>

                <div class="col-6">
                    <?= $car->getDescription(); ?>
                </div>
            </div>

            <?php $this->loadPartial('booking', [
                'carId' => $car->getId()
            ]); ?>
        </aside>

        <aside class="col-4 bg-light p-4">
            <?= $this->loadPartial('search'); ?>
        </aside>
    </div>
</section>